language: bash

dist: disco

matrix:
  fast_finish: true

cache: false

addons:
  apt:
    packages:
    - shellcheck
    update: true

services:
  - docker

    #before_install:
    #  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    #  - docker pull marcosj/rpi_raspbian:buster


install:
  - shellcheck --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t openhabian/rpi-openhabian -f Dockerfile.openhabian .

jobs:
  include:
    - stage: Devtests
      script:
        - docker run -it openhabian/rpi-openhabian bash -c 'bats -r -f "dev-." .'
    - stage: Openhabian-Setup
      script:
        - docker run --name "openhabian-test" --privileged -d openhabian/rpi-openhabian
        - travis_wait 60 sleep infinity & docker exec -it "openhabian-test" bash -c './build.bash local-test; mv ~/.profile ~/.bash_profile; /etc/rc.local'
        - docker commit "openhabian-test" openhabian-installed
    - stage: Bats
      script: docker run -it openhabian/rpi-openhabian bash -c 'bats -r -f "unit-." .'
    - script:
        - docker run --name "bats-tests" --privileged -d openhabian-installed
        - travis_wait 60 sleep infinity & docker exec -it "bats-tests" bash -c 'bats -r -f "installation-." .'
        - travis_wait 60 sleep infinity & docker exec -it "bats-tests" bash -c 'bats -r -f "destructive-." .'
    - stage: Shellcheck
      script: shellcheck -x -s bash openhabian-setup.sh || true
    - script: shellcheck -x -s bash functions/*.bash || true
    - script: shellcheck -x -s bash build-image/*.bash || true
