language: shell
os: linux
# using latest Ubuntu (not the travis-ci default) to get latest tool versions in Travis environment
dist: bionic

cache: false

addons:
  apt:
    packages:
    - shellcheck
    - virt-what
    update: true

git:
  submodules: false
  quiet: true

services:
  - docker

stages:
  - Dev & Unit tests
  - BATS and shellcheck tests
  - Run unattended openHABian installation

install:
# prepare configuration for tests, select debug level here:
  - sed -iE 's#mode=.*$#mode=unattended_debug#' build-image/openhabian.conf
  - #sed -iE 's#mode=.*$#mode=debug_maximum#' build-image/openhabian.conf
  - echo "Cloning openHABian repo from https://github.com/${TRAVIS_REPO_SLUG}.git"
  - sed -i 's#repositoryurl=https://github.com/openhab/openhabian.git#repositoryurl=https://github.com/'${TRAVIS_REPO_SLUG}'.git#' build-image/openhabian.conf
  - sed -i 's#clonebranch=master#clonebranch='${TRAVIS_BRANCH}'#' build-image/openhabian.conf

jobs:
  fast_finish: true
  allow_failures:
    - arch: arm64
  include:
    - stage: Dev & Unit tests
      env: aarch64
      arch: arm64
      script:
        - sed -i 's/java_arch=32-bit$/java_arch=64-bit/' build-image/openhabian.conf
        - docker build -t openhabian/dev-openhabian -f Dockerfile.openhabian-aarch64-native .
        - docker run -i openhabian/dev-openhabian bash -c '/usr/local/bin/bats -r -f "dev-." .'
        - docker run -i openhabian/dev-openhabian bash -c '/usr/local/bin/bats -r -f "unit-." .'
    - stage: BATS and shellcheck tests
      env: aarch64
      arch: arm64
      script:
      - docker build -t openhabian/bats-openhabian -f Dockerfile.openhabian-aarch64-native .
      - docker run --name "bats-inst-tests" -d openhabian/bats-openhabian bash -c '/usr/local/bin/bats -r -f "installation-." .'
      - docker run --name "bats-dest-tests" -d openhabian/bats-openhabian bash -c '/usr/local/bin/bats -r -f "destructive-." .'
      - shellcheck -x -s bash openhabian-setup.sh && echo "shellcheck openhabian-setup.sh - OK"; 
        shellcheck -x -s bash functions/*.bash && echo "shellcheck functions/*.bash - OK"; 
        shellcheck -x -s bash build-image/*.bash && echo "shellcheck build-image/*.bash - OK";
        shellcheck -x -s bash build.bash && echo "shellcheck build.bash - OK"
    - stage: Run unattended openHABian installation
      env: amd64
      script:
        - export HW=x86
        - sed -i 's/java_arch=32-bit$/java_arch=64-bit/' build-image/openhabian.conf
        - docker build -t openhabian/${HW}-openhabian -f Dockerfile.openhabian-x86 .
        - echo -e "\n\e[36mopenHABian test installation starting on virtual $HW on $arch ..."
        - docker run --name "openhabian-${HW}" -d openhabian/${HW}-openhabian;
          docker exec -i "openhabian-${HW}" bash -c \
            'VIRT=$(sudo virt-what); echo -e "\n\e[37mTesting openhabian install on ${VIRT} ...\n"; ./build.bash local-test && mv ~/.profile ~/.bash_profile && /etc/rc.local'
    - env: arm32hf
      script:
        - export HW=rpi2
        - docker run --rm --privileged multiarch/qemu-user-static:register --reset
        - sed -i 's/java_arch=64-bit$/java_arch=32-bit/' build-image/openhabian.conf
        - docker build -t openhabian/${HW}-openhabian -f Dockerfile.openhabian-arm32hf-emulated .
        - echo -e "\n\e[36mopenHABian test installation starting on virtual $HW on $arch ..."
        - docker run --name "openhabian-${HW}" -d openhabian/${HW}-openhabian;
          docker exec -i "openhabian-${HW}" bash -c \
            'VIRT=$(sudo virt-what); echo -e "\n\e[37mTesting openhabian install on ${VIRT} ...\n"; ./build.bash local-test && mv ~/.profile ~/.bash_profile && /etc/rc.local'
    - env: arm32hf
      arch: arm64
      script:
        - export HW=rpi2
        - sed -i 's/java_arch=64-bit$/java_arch=32-bit/' build-image/openhabian.conf
        - docker build -t openhabian/${HW}-openhabian -f Dockerfile.openhabian-arm32hf-native .
        - echo -e "\n\e[36mopenHABian test installation starting on virtual $HW on $arch ..."
        - docker run --name "openhabian-${HW}" -d openhabian/${HW}-openhabian;
          docker exec -i "openhabian-${HW}" bash -c \
            'VIRT=$(sudo virt-what); echo -e "\n\e[37mTesting openhabian install on ${VIRT} ...\n"; ./build.bash local-test && mv ~/.profile ~/.bash_profile && /etc/rc.local'
    - env: aarch64
      arch: arm64
      script:
        - export HW=rpi3
        - sed -i 's/java_arch=32-bit$/java_arch=64-bit/' build-image/openhabian.conf
        - docker build -t openhabian/${HW}-openhabian -f Dockerfile.openhabian-aarch64-native .
        - echo -e "\n\e[36mopenHABian test installation starting on virtual $HW on $arch ..."
        - docker run --name "openhabian-${HW}" -d openhabian/${HW}-openhabian;
          docker exec -i "openhabian-${HW}" bash -c \
            'VIRT=$(sudo virt-what); echo -e "\n\e[37mTesting openhabian install on ${VIRT} ...\n"; ./build.bash local-test && mv ~/.profile ~/.bash_profile && /etc/rc.local'
    - env: aarch64
      arch: arm64
      script:
        - export HW=rpi4
        - sed -i 's/java_arch=32-bit$/java_arch=64-bit/' build-image/openhabian.conf
        - docker build -t openhabian/${HW}-openhabian -f Dockerfile.openhabian-aarch64-64bit .
        - echo -e "\n\e[36mopenHABian test installation starting on virtual $HW on $arch ..."
        - docker run --name "openhabian-${HW}" -d openhabian/${HW}-openhabian;
          docker exec -i "openhabian-${HW}" bash -c \
            'VIRT=$(sudo virt-what); echo -e "\n\e[37mTesting openhabian install on ${VIRT} ...\n"; ./build.bash local-test && mv ~/.profile ~/.bash_profile && /etc/rc.local'

