language: bash

addons:
  apt:
    packages:
    - shellcheck
    update: true

services:
  - docker

install:
  - shellcheck --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t openhabian/openhabian-bats -f Dockerfile.bats .
  - docker build -t openhabian/rpi-openhabian -f Dockerfile.openhabian .

script:
  - docker run --name bats -d -it openhabian/openhabian-bats bash -c 'bats -r -f "unit-." .'
    #  - docker exec -it bats bash -c './build.bash local-test && mv ~/.profile ~/.bash_profil && /etc/rc.local'
    #  - docker exec -it bats bash -c 'bats -r -f "installation-." .'
    #  - docker exec -it bats bash -c 'bats -r -f "destructive-." .'
  - docker run --name openhabian-test -e TINI_SUBREAPER= -it -d openhabian/rpi-openhabian

  - shellcheck -s bash openhabian-setup.sh || true
  - shellcheck -s bash functions/*.bash || true
  - shellcheck -s bash build-image/*.bash || true
