language: bash

dist: disco

jobs:
  include:
    - stage: openhabian-setup
      script:
        - docker run --name "openhabian-test" --privileged -d openhabian/rpi-openhabian
        - docker exec -it "openhabian-test" bash -c './build.bash local-test && mv ~/.profile ~/.bash_profil && /etc/rc.local'
        - docker commit "openhabian-test" openhabian-installed
    - script: docker run -it openhabian/rpi-openhabian bash -c 'mkdir /var/lib/openhab2; bats -r -f "dev-zram" .'
    - script: shellcheck -x -s bash openhabian-setup.sh || true
    - script: shellcheck -x -s bash functions/*.bash || true
    - script: shellcheck -x -s bash build-image/*.bash || true
    - stage: main
      script:
        - docker run --name "bats-tests" --privileged -d openhabian-installed
        - docker exec -it "bats-tests" bash -c 'bats -r -f "installation-." .'
        - docker exec -it "bats-tests" bash -c 'bats -r -f "destructive-." .'
    - script: docker run -it openhabian/rpi-openhabian bash -c 'bats -r -f "unit-." .'

matrix:
  fast_finish: true

cache: false

addons:
  apt:
    packages:
    - shellcheck
    update: true

services:
  - docker

install:
  - shellcheck --version
  - docker run --rm --privileged multiarch/qemu-user-static:register --reset
  - docker build -t openhabian/rpi-openhabian -f Dockerfile.openhabian .

<<<<<<< HEAD
jobs:
  include:
    - stage: Devtests
      script:
        - docker run -it openhabian/rpi-openhabian bash -c 'bats -r -f "dev-." .'
    - stage: Openhabian-Setup
      script:
        - docker run --name "openhabian-test" --privileged -d openhabian/rpi-openhabian
        - travis_wait 60 sleep infinity & docker exec -it "openhabian-test" bash -c './build.bash local-test; mv ~/.profile ~/.bash_profile; /etc/rc.local'
        - docker commit "openhabian-test" openhabian-installed
    - stage: Bats
      script: docker run -it openhabian/rpi-openhabian bash -c 'bats -r -f "unit-." .'
    - script:
        - docker run --name "bats-tests" --privileged -d openhabian-installed
        - travis_wait 60 sleep infinity & docker exec -it "bats-tests" bash -c 'bats -r -f "installation-." .'
        - travis_wait 60 sleep infinity & docker exec -it "bats-tests" bash -c 'bats -r -f "destructive-." .'
    - stage: Shellcheck
      script: shellcheck -x -s bash openhabian-setup.sh || true
    - script: shellcheck -x -s bash functions/*.bash || true
    - script: shellcheck -x -s bash build-image/*.bash || true
=======
    #script:
        #  - docker run --name openhabian-test --privileged -d openhabian/rpi-openhabian
        #  - docker exec -it "openhabian-test" bash -c $TEST_CMD
    #  - docker exec -it "openhabian-test" bash -c 'bats -r -f "unit-." .'
    #  - #docker exec -it "openhabian-test" bash -c './build.bash local-test && mv ~/.profile ~/.bash_profil; /etc/rc.local'
    #  - #docker exec -it "openhabian-test" bash -c 'bats -r -f "installation-." .'
    #  - travis_wait 30 docker exec -it "openhabian-test" bash -c 'bats -r -f "destructive-." .'

    #  - shellcheck -x -s bash openhabian-setup.sh || true
    #  - shellcheck -x -s bash functions/*.bash || true
    #  - shellcheck -x -s bash build-image/*.bash || true
>>>>>>> f51b286... build system refactored
